// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgE2wfbauDC1iJYfOyx5hEvESclFopiCY',
    appId: '1:673691526468:web:bab3b692720226c386e311',
    messagingSenderId: '673691526468',
    projectId: 'weather-app-7960d',
    authDomain: 'weather-app-7960d.firebaseapp.com',
    storageBucket: 'weather-app-7960d.firebasestorage.app',
    measurementId: 'G-RHFW0ZGYP2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIWNzpH-_5iYpLAxxRvt5f0KUUzV-uX3s',
    appId: '1:673691526468:android:afcc6fc72c3434ec86e311',
    messagingSenderId: '673691526468',
    projectId: 'weather-app-7960d',
    storageBucket: 'weather-app-7960d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8SVZiTEmTdgWi5k4Lhxrb9Ie7YJmrcHs',
    appId: '1:673691526468:ios:83c7dd8350ff1d0386e311',
    messagingSenderId: '673691526468',
    projectId: 'weather-app-7960d',
    storageBucket: 'weather-app-7960d.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8SVZiTEmTdgWi5k4Lhxrb9Ie7YJmrcHs',
    appId: '1:673691526468:ios:83c7dd8350ff1d0386e311',
    messagingSenderId: '673691526468',
    projectId: 'weather-app-7960d',
    storageBucket: 'weather-app-7960d.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgE2wfbauDC1iJYfOyx5hEvESclFopiCY',
    appId: '1:673691526468:web:7eee8202956019e386e311',
    messagingSenderId: '673691526468',
    projectId: 'weather-app-7960d',
    authDomain: 'weather-app-7960d.firebaseapp.com',
    storageBucket: 'weather-app-7960d.firebasestorage.app',
    measurementId: 'G-8Y37857KYB',
  );
}
